name: Prompt Deploy (Merge - Prod)

on:
  push:
    branches: [ main ]

jobs:
  process-prompts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3 jinja2

      - name: Run Prompt Processor (Prod)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET_PROD: ${{ secrets.S3_BUCKET_PROD }}
          DEPLOY_ENV: prod
        run: |
          python process_prompt.py
